services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meterscanwatergas
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 4000:4000    
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/meterscanwatergas"

volumes:
  postgres-volume:
