services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env

  api:
    container_name: api
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - postgres
